---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: portal-backoffice

replicas:
  - name: portal-backoffice
    count: 2

images:
  - name: ghcr.io/london-bridge/bo-portal/backend
    newTag: latest

patches:
  # ConfigMap patch for environment-specific values
  - target:
      kind: ConfigMap
      name: shared-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: staging
      # TODO: Adicionar patches específicos quando o código fonte estiver disponível

  # Deployment patches
  - target:
      kind: Deployment
      name: portal-backoffice
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: staging
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
