---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: portal-backoffice

replicas:
  # TODO: Ajustar quando o código fonte estiver disponível
  # - name: portal-backoffice
  #   count: 1

images:
  # TODO: Ajustar quando o código fonte estiver disponível
  # - name: ghcr.io/london-bridge/portal_backoffice
  #   newTag: qa-latest

patches:
  # ConfigMap patch for environment-specific values
  - target:
      kind: ConfigMap
      name: shared-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: qa
      # TODO: Adicionar patches específicos quando o código fonte estiver disponível

  # TODO: Adicionar patches de deployment quando o código fonte estiver disponível
  # - target:
  #     kind: Deployment
  #     name: portal-backoffice
  #   patch: |-
  #     - op: add
  #       path: /spec/template/spec/nodeSelector
  #       value:
  #         role: qa
  #     - op: replace
  #       path: /spec/template/spec/imagePullSecrets/0/name
  #       value: regcred
