---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shared-configmap.yaml
  - service-account.yaml
  - ghcr-credentials-secret.yaml
  - rds-ca-cert-configmap.yaml
  - portal-backoffice-secret.yaml
  - portal-backoffice-deployment.yaml
  - portal-backoffice-service.yaml
  - portal-backoffice-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: portal-backoffice
