---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shared-configmap.yaml
  - portal-backoffice-deployment.yaml
  - portal-backoffice-service.yaml

commonLabels:
  app.kubernetes.io/part-of: portal-backoffice
